### ISSUE TITLE
Remove startup messages "/Finder [TBC]:: by Avael.... has loaded \o/"

### ISSUE THREAD

**Issue by Bonkeybee** [Haatveit88/finder-addon#2]
Please add an option or remove the addon startup messages from chat.

**Comment by haatveit88** [comment]
Latest version now has a toggle for the login message. It will still print a message if there's a problem with the Item Cache, but normally nothing.

You can toggle this option using `/finder greeting`

I should have done this long ago, but never got around to it, so thank you for raising the issue!
