### ISSUE TITLE
Does not load on WotLK build

### ISSUE THREAD

**Issue by ajames27** [Haatveit88/finder-addon#3]
The addon does not load on the WotLK pre-patch build. Is it possible that this could be updated to be compatible with the new patch?

This addon is a lifesaver and I hope it gets updated soon!

Thanks!

**Comment by haatveit88** [comment]
Hi, glad to hear that people are still finding a use for my AddOn!

I don't play anymore myself, so it's hard to test any fixes without a
subscription. I will try to do a basic update that I think might help, in
the next few days.

**Comment by haatveit88** [comment]
This has now been resolved and a new version is pushed to GitHub and Curse!
